"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const body_parser_1 = __importDefault(require("body-parser"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
const cors_1 = __importDefault(require("cors"));
require('dotenv').config();
const userController_1 = __importDefault(require("./controllers/userController"));
const userService_1 = __importDefault(require("./services/userService"));
const userRoutes_1 = __importDefault(require("./routes/userRoutes"));
const userModel_1 = __importDefault(require("./models/userModel"));
const classesController_1 = __importDefault(require("./controllers/classesController"));
const classesServices_1 = __importDefault(require("./services/classesServices"));
const classesRoutes_1 = __importDefault(require("./routes/classesRoutes"));
const classesModel_1 = __importDefault(require("./models/classesModel"));
const classBookingsController_1 = __importDefault(require("./controllers/classBookingsController"));
const classBookingsServices_1 = __importDefault(require("./services/classBookingsServices"));
const classBookingsRoutes_1 = __importDefault(require("./routes/classBookingsRoutes"));
const classBookingsModel_1 = __importDefault(require("./models/classBookingsModel"));
const classSchedulesController_1 = __importDefault(require("./controllers/classSchedulesController"));
const classSchedulesServices_1 = __importDefault(require("./services/classSchedulesServices"));
const classSchedulesRoutes_1 = __importDefault(require("./routes/classSchedulesRoutes"));
const classSchedulesModel_1 = __importDefault(require("./models/classSchedulesModel"));
const personalController_1 = __importDefault(require("./controllers/personalController"));
const personalService_1 = __importDefault(require("./services/personalService"));
const personalModel_1 = __importDefault(require("./models/personalModel"));
const rolesModel_1 = __importDefault(require("./models/rolesModel"));
const personalRoutes_1 = __importDefault(require("./routes/personalRoutes"));
const abonementController_1 = __importDefault(require("./controllers/abonementController"));
const abonementService_1 = __importDefault(require("./services/abonementService"));
const abonementModel_1 = __importDefault(require("./models/abonementModel"));
const abonementRoutes_1 = __importDefault(require("./routes/abonementRoutes"));
const userAbonementController_1 = __importDefault(require("./controllers/userAbonementController"));
const userAbonementService_1 = __importDefault(require("./services/userAbonementService"));
const userAbonModel_1 = __importDefault(require("./models/userAbonModel"));
const userAbonementRoutes_1 = __importDefault(require("./routes/userAbonementRoutes"));
const app = (0, express_1.default)();
const port = Number(process.env.PORT);
const corsOptions = {
    origin: process.env.CLIENT_URL,
    credentials: true,
};
app.use((0, cors_1.default)(corsOptions));
app.use(body_parser_1.default.json());
app.use((0, cookie_parser_1.default)());
const userService = new userService_1.default(userModel_1.default);
const userController = new userController_1.default(userService);
const userRouter = (0, userRoutes_1.default)(userController);
const classBookingsService = new classBookingsServices_1.default(classBookingsModel_1.default);
const classBookingsController = new classBookingsController_1.default(classBookingsService);
const classBookingsRouter = (0, classBookingsRoutes_1.default)(classBookingsController);
const classesService = new classesServices_1.default(classesModel_1.default);
const classesController = new classesController_1.default(classesService);
const classesRouter = (0, classesRoutes_1.default)(classesController);
const classScheduleService = new classSchedulesServices_1.default(classSchedulesModel_1.default);
const classScheduleController = new classSchedulesController_1.default(classScheduleService);
const classSheduleRouter = (0, classSchedulesRoutes_1.default)(classScheduleController);
const abonementService = new abonementService_1.default(abonementModel_1.default);
const abonementController = new abonementController_1.default(abonementService);
const abonementRouter = (0, abonementRoutes_1.default)(abonementController);
const personalService = new personalService_1.default(personalModel_1.default, rolesModel_1.default);
const personalController = new personalController_1.default(personalService);
const personalRouter = (0, personalRoutes_1.default)(personalController);
const userAbonementService = new userAbonementService_1.default(userAbonModel_1.default);
const userAbonementController = new userAbonementController_1.default(userAbonementService);
const userAbonementRouter = (0, userAbonementRoutes_1.default)(userAbonementController);
app.use('/api', userRouter);
app.use('/api', classesRouter);
app.use('/api', classBookingsRouter);
app.use('/api', classSheduleRouter);
app.use('/api', personalRouter);
app.use('/api', abonementRouter);
app.use('/api', userAbonementRouter);
app.listen(port, '0.0.0.0', () => {
    console.log(`SERVER STARTED ON PORT 0.0.0.0:${port}`);
});
